#!/bin/bash

echo "🔧 Fixing Cloudinary Environment Variables in Vercel Production"
echo ""
echo "Please manually set these in Vercel Dashboard:"
echo "https://vercel.com/das-48ca2629/merry-360-frontend/settings/environment-variables"
echo ""
echo "Required Variables for Production:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. VITE_CLOUDINARY_CLOUD_NAME"
echo "   Value: dml5w7t0u"
echo ""
echo "2. VITE_CLOUDINARY_UPLOAD_PRESET"
echo "   Value: ml_default"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Steps:"
echo "1. Click 'Edit' on VITE_CLOUDINARY_CLOUD_NAME"
echo "2. Enter: dml5w7t0u"
echo "3. Click 'Save'"
echo "4. Click 'Edit' on VITE_CLOUDINARY_UPLOAD_PRESET"
echo "5. Enter: ml_default"
echo "6. Click 'Save'"
echo "7. Go to Deployments and click 'Redeploy' on the latest one"
echo ""
echo "Or run: vercel --prod"
echo ""
